version: "3.9"
services:
  app:
    build:
      context: .
    environment:
      - DATABASE_URL=${DATABASE_URL}  # Переменная из .env.docker
    env_file:
      - .env.docker
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
